---
project_name: testit

archives:
  - id: testit
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      386: 32bit
      amd64: 64bit
      darwin: macOS
      linux: Linux

brews:
  - name: testit
    caveats:
    commit_author:
      name: Kamil Samigullin
      email: kamil@samigullin.info
    description: Extended testing toolset.
    folder: Formula
    homepage: https://github.com/octolab/testit
    tap:
      owner: octolab
      name: homebrew-tap
    install: |
      bin.install "testit"

      output = Utils.popen_read("#{bin}/testit completion bash")
      (bash_completion/"testit").write output

      output = Utils.popen_read("#{bin}/testit completion fish")
      (fish_completion/"testit.fish").write output

      output = Utils.popen_read("#{bin}/testit completion zsh")
      (zsh_completion/"_testit").write output

      prefix.install_metafiles
    test: |
      system "#{bin}/testit version"

builds:
  - id: testit
    binary: testit
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - 386
      - amd64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: octolab
    name: testit
